name: Update license data

on:
  workflow_dispatch:
  schedule:
  - cron: "13 13 13 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn
      - name: Compile TypeScript
        run: yarn build
      - name: Update data
        run: node dist/updater
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
